In [42]:
import pandas as pd
import matplotlib.pyplot as plt

In [43]:
df  =  pd.read_csv("olist_orders_dataset.new.csv")

In [44]:
df.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00

In [45]:
df["order_approved_at"]=df["order_approved_at"].fillna("status pending")

In [ ]:
# date_columns = [
#     "order_purchase_timestamp",
#     "order_approved_at",
#     "order_delivered_carrier_date",
#     "order_delivered_customer_date",
#     "order_estimated_delivery_date"
# ]

# for col in date_columns:
#     df[col] = pd.to_datetime(
#         df[col],
#         format="%d-%m-%Y %H:%M",
#         errors="coerce"
#     )

In [179]:
df[df["order_id"]=="0b16257b1b7ee0922ea03954f2cae85a"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
92108,0b16257b1b7ee0922ea03954f2cae85a,b0344db4bb1741ab32ee52ef092b2572,canceled,2018-08-07 18:31:25,2018-08-07 18:44:50,NaN,NaN,2018-08-10 00:00:00

In [99]:
df[df["order_delivered_carrier_date"].isna()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
266,8e24261a7e58791d10cb1bf9da94df5c,64a254d30eed42cd0e6c36dddb88adf0,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaN,NaN,2017-12-05 00:00:00
324,d3c8851a6651eeff2f73b0e011ac45d0,957f8e082185574de25992dc659ebbc0,processing,2016-10-05 22:44:13,2016-10-06 15:51:05,NaN,NaN,2016-12-09 00:00:00
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,status pending,NaN,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,status pending,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00

In [100]:
df[df["order_delivered_customer_date"].isna()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaN,2018-02-07 00:00:00
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,status pending,NaN,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,status pending,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00

In [72]:
df["order_delivered_carrier_date"]=df["order_delivered_carrier_date"].fillna("pending")

In [73]:
df["order_delivered_customer_date"]=df["order_delivered_customer_date"].fillna("pending")

In [70]:
df["order_approved_at"]=df["order_approved_at"].fillna("pending")

In [58]:
df["estimated_vs_actual_days"]=df["estimated_vs_actual_days"].fillna(0)

In [175]:
df[df["estimated_vs_actual_days"]==0]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_hours,estimated_vs_actual_days,purchased_year,purchased_hour,purchased_weekday,purchased_month,day_type,delivery_days
78,6d25592267349b322799e2beb687871e,5bb39c890c91b1d26801aa19a9336eac,delivered,2018-08-26 22:04:34,2018-08-28 04:10:18,2018-08-28 12:56:00,2018-08-29 12:40:53,2018-08-30,30.095556,0.0,2018,22,Sunday,August,Weekend,2.0
120,ee0c5c649e17808bc4a363d3a80ebf85,cc3590e4afbb4b3e056b50a80a6a7d0c,delivered,2018-01-30 07:51:17,2018-01-30 08:13:43,2018-01-31 15:06:03,2018-02-20 15:25:04,2018-02-21,0.373889,0.0,2018,7,Tuesday,January,Weekday,21.0
237,c263211bd219538f7c031591e87ef0d7,ed8c52327eecff596e141636d5b556d2,delivered,2017-11-24 16:56:46,2017-11-28 03:48:24,2017-12-08 23:28:26,2017-12-18 20:24:54,2017-12-19,82.860556,0.0,2017,16,Friday,November,Weekday,24.0
260,f419e615bbdeb34741d4bdd661ff8599,271f76c70ce217ee656713b99097eaef,delivered,2018-08-08 10:49:59,2018-08-08 11:05:15,2018-08-10 13:40:00,2018-08-16 19:18:51,2018-08-17,0.254444,0.0,2018,10,Wednesday,August,Weekday,8.0
271,6f954a919130aa1e8def4ed1b9fca432,d929280e89af72c9509d90a5912adaa4,delivered,2018-07-28 18:21:00,2018-07-31 03:50:25,2018-07-31 11:13:00,2018-08-01 23:57:28,2018-08-02,57.490278,0.0,2018,18,Saturday,July,Weekend,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99021,385de753cc8af8758bf66d29d9916e66,83cc2c8ce60cb5aa51122ccb4bee73eb,delivered,2017-09-06 11:47:44,2017-09-07 02:50:39,2017-09-12 20:03:13,2017-09-18 18:47:49,2017-09-19,15.048611,0.0,2017,11,Wednesday,September,Weekday,12.0
99068,9afb4dbb97ba2e4b69f72df48c4cf901,1f3e5065ebd28abed905c82bd83b4594,delivered,2018-08-14 10:01:17,2018-08-14 10:15:25,2018-08-14 13:54:00,2018-08-16 16:05:42,2018-08-17,0.235556,0.0,2018,10,Tuesday,August,Weekday,2.0
99167,ad005b5bdc8ec1f3085f0967211207d1,d765f7544b62372aafab58ba0ca7d0f6,delivered,2018-08-05 10:50:43,2018-08-05 11:05:07,2018-08-06 16:27:00,2018-08-08 16:23:48,2018-08-09,0.24,0.0,2018,10,Sunday,August,Weekend,3.0
99394,079c9f53e6c3253320db701a645b0b9a,e5e0698e95094be297436cbd55c2dcad,delivered,2018-08-09 20:33:45,2018-08-09 20:50:17,2018-08-13 14:20:00,2018-08-16 17:51:09,2018-08-17,0.275556,0.0,2018,20,Thursday,August,Weekday,6.0
99407,c2af225ac9a68a3c24500aa6fab006aa,f93c9e539a9705a57902c625b611e90c,delivered,2018-08-20 10:04:30,2018-08-20 14:53:46,2018-08-22 13:16:00,2018-08-27 21:44:45,2018-08-28,4.821111,0.0,2018,10,Monday,August,Weekday,7.0

In [59]:
df["approval_hours"]=df["approval_hours"].fillna(0)

In [60]:
df["purchased_year"]=df["purchased_year"].fillna(0)

In [110]:
df[df["approval_hours"].isna()]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, approval_hours, estimated_vs_actual_days]
Index: []

In [170]:
df["delivery_days"] = df["delivery_days"].replace("pending", 0)

In [173]:
df[df["delivery_days"]==0]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_hours,estimated_vs_actual_days,purchased_year,purchased_hour,purchased_weekday,purchased_month,day_type,delivery_days
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,pending,pending,2017-05-09,49.0525,pending,2017,12,Tuesday,April,Weekday,0.0
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,pending,2018-06-28,11.775,pending,2018,16,Monday,June,Weekday,0.0
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,pending,pending,2018-08-21,84.508889,pending,2018,17,Friday,August,Weekday,0.0
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,pending,pending,2017-10-03,0.135,pending,2017,14,Sunday,September,Weekend,0.0
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,pending,2018-02-07,14.989722,pending,2018,11,Wednesday,January,Weekday,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,pending,pending,pending,2018-10-01,pending,pending,2018,16,Friday,August,Weekday,0.0
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,pending,pending,2018-02-06,80.178056,pending,2018,23,Friday,January,Weekday,0.0
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,pending,pending,pending,2018-09-27,pending,pending,2018,18,Thursday,September,Weekday,0.0
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,pending,pending,2017-09-15,119.278611,pending,2017,16,Wednesday,August,Weekday,0.0
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,pending,pending,2017-10-23,103.765,pending,2017,10,Tuesday,October,Weekday,0.0

In [74]:
df.isna().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
approval_hours                   0
estimated_vs_actual_days         0
purchased_year                   0
purchased_hour                   0
purchased_weekday                0
purchased_month                  0
delivery_days                    0
day_type                         0
dtype: int64

In [77]:
df.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
approval_hours                          float64
estimated_vs_actual_days                float64
purchased_year                            int32
purchased_hour                            int32
purchased_weekday                        object
purchased_month                          object
delivery_days                           float64
day_type                                 object
dtype: object

In [76]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_estimated_delivery_date",
    "order_delivered_customer_date",
    "order_delivered_carrier_date" 
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

print(df[date_cols].dtypes)

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
dtype: object

In [78]:
df.shape

(99441, 16)

In [50]:
df["approval_hours"] = (
    df["order_approved_at"] -
    df["order_purchase_timestamp"]
).dt.total_seconds() / 3600

df["estimated_vs_actual_days"] = (
    df["order_estimated_delivery_date"] -
    df["order_delivered_customer_date"]
).dt.days

In [188]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_estimated_delivery_date",
    "order_delivered_customer_date"
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

print(df[date_cols].dtypes)  # sanity check — should all say datetime64[ns]

df["approval_hours"] = (
    df["order_approved_at"] - df["order_purchase_timestamp"]
).dt.total_seconds() / 3600

df["estimated_vs_actual_days"] = (
    df["order_estimated_delivery_date"] - df["order_delivered_customer_date"]
).dt.days

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
order_delivered_customer_date    datetime64[ns]
dtype: object

In [52]:
df["purchased_year"] = (df["order_purchase_timestamp"]).dt.year
df["purchased_hour"] = (df["order_purchase_timestamp"]).dt.hour
df["purchased_weekday"] = (df["order_purchase_timestamp"]).dt.day_name()
df["purchased_month"] = (df["order_purchase_timestamp"]).dt.month_name()

In [190]:
df.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_hours,estimated_vs_actual_days,purchased_year,purchased_hour,purchased_weekday,purchased_month
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,0.178333,7.0,2017,10,Monday,October
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,30.713889,5.0,2018,20,Tuesday,July
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,0.276111,17.0,2018,8,Wednesday,August
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,0.298056,12.0,2017,19,Saturday,November
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1.030556,9.0,2018,21,Tuesday,February
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01,0.218889,5.0,2017,21,Sunday,July
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09,49.052500,NaN,2017,12,Tuesday,April
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07,0.194722,11.0,2017,13,Tuesday,May
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06,32.360556,31.0,2017,18,Monday,January
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23,0.175000,6.0,2017,11,Saturday,July

In [21]:
df["estimated_vs_actual_days"]=df["estimated_vs_actual_days"].fillna("pending")

In [64]:
df["delivery_days"]=df["delivery_days"].fillna(0)

In [219]:
df[df["order_id"]=="13d341318c77969f10d77e1382957542"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_hours,estimated_vs_actual_days,purchased_year,purchased_hour,purchased_weekday,purchased_month,day_type,delivery_days
74718,13d341318c77969f10d77e1382957542,3b6cfa5c62f4bfb3c09652d9ac539a8d,canceled,2018-08-01 09:43:22,2018-08-02 05:30:46,pending,pending,2018-08-08,19.79,0.0,2018,9,Wednesday,August,Weekday,0.0

In [54]:
df["is_weekend"] = df["order_purchase_timestamp"].dt.dayofweek >= 5  # 5=Saturday, 6=Sunday

df["day_type"] = df["is_weekend"].map({
    True: "Weekend",
    False: "Weekday"
})

In [55]:
df = df.drop("is_weekend",axis = 1)

In [53]:
df["delivery_days"] = (
    df["order_delivered_customer_date"] -
    df["order_purchase_timestamp"]
).dt.days

In [195]:
df[df["delivery_days"].isna()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_hours,estimated_vs_actual_days,purchased_year,purchased_hour,purchased_weekday,purchased_month,day_type,delivery_days
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09,49.052500,NaN,2017,12,Tuesday,April,Weekday,NaN
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaT,2018-06-28,11.775000,NaN,2018,16,Monday,June,Weekday,NaN
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaT,NaT,2018-08-21,84.508889,NaN,2018,17,Friday,August,Weekday,NaN
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaT,NaT,2017-10-03,0.135000,NaN,2017,14,Sunday,September,Weekend,NaN
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaT,2018-02-07,14.989722,NaN,2018,11,Wednesday,January,Weekday,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaT,NaT,NaT,2018-10-01,NaN,NaN,2018,16,Friday,August,Weekday,NaN
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaT,NaT,2018-02-06,80.178056,NaN,2018,23,Friday,January,Weekday,NaN
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaT,NaT,NaT,2018-09-27,NaN,NaN,2018,18,Thursday,September,Weekday,NaN
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaT,NaT,2017-09-15,119.278611,NaN,2017,16,Wednesday,August,Weekday,NaN
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaT,NaT,2017-10-23,103.765000,NaN,2017,10,Tuesday,October,Weekday,NaN

In [81]:
df.shape

(99441, 16)

In [210]:
df["purchased_hour"]=df["purchased_hour"].fillna(0)

In [80]:
df["purchased_year"].isna().sum()
df["purchased_hour"].isna().sum()

0

In [79]:
df.to_csv("olist_orders_new.csv", index=False)

In [34]:
df["estimated_vs_actual_days"]=df["estimated_vs_actual_days"].astype(float)

ValueError: could not convert string to float: 'pending'